version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 2519
      POSTGRES_DB: aifs
    ports: ["5432:5432"]
    volumes: [pg:/var/lib/postgresql/data]
  redis:
    image: redis:7
    ports: ["6379:6379"]
volumes:
<<<<<<< HEAD
  pg: {}
=======
  pg: {}
>>>>>>> 91a16942160d47dfadf241795dde0cff6593b312
